export enum EIpcChannel {
  CHAT = 'CHAT',
  ENV = 'ENV',
  MODEL = 'MODEL',
  SETTINGS = 'SETTINGS',
  PROMPT_SELECTOR = 'PROMPT_SELECTOR',
}

export enum EIpcEvent {
  CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE',
  ENV_GET = 'ENV_GET',
  MODEL_LIST = 'MODEL_LIST',
  SETTINGS_LOAD = 'SETTINGS_LOAD',
  SETTINGS_SAVE = 'SETTINGS_SAVE',
  PROMPT_SELECT = 'PROMPT_SELECT',
}
