export enum EIpcRendererEvent {
  CHAT_WINDOW_DATA = 'CHAT_WINDOW_DATA',
  OLLAMA_RESPONSE = 'OLLAMA_RESPONSE',
  PROMPT_SELECTOR_DATA = 'PROMPT_SELECTOR_DATA',
  CHAT_TITLE_UPDATED = 'CHAT_TITLE_UPDATED',
}
