export enum EIpcRendererEvent { // TODO: split to request - response and backend events
  CHAT_CREATED = 'CHAT_CREATED',
  CHAT_DELETED = 'CHAT_DELETED',
  CHAT_FOLLOW_UP_QUESTIONS = 'CHAT_FOLLOW_UP_QUESTIONS',
  CHAT_LOAD_MESSAGES_DATA = 'CHAT_LOAD_MESSAGES_DATA',
  CHAT_STREAM_CHUNK = 'CHAT_STREAM_CHUNK',
  CHAT_STREAM_END = 'CHAT_STREAM_END',
  CHAT_TITLE_UPDATED = 'CHAT_TITLE_UPDATED', // TODO: combine with CHAT_CREATED
  OLLAMA_RESPONSE = 'OLLAMA_RESPONSE', // TODD: REPLACE all OLLAMA occurrences to more abstract LLM
  PROMPT_SELECTED = 'PROMPT_SELECTED',
  PROMPT_SELECTOR_DATA = 'PROMPT_SELECTOR_DATA',
}
