export enum EIpcChannel {
  CHAT = 'CHAT',
  ENV = 'ENV',
  MODEL = 'MODEL',
  SETTINGS = 'SETTINGS',
  PROMPT_SELECTOR = 'PROMPT_SELECTOR',
}

export enum EIpcEvent {
  CHAT_CREATE_SESSION = 'CHAT_CREATE_SESSION',
  CHAT_DELETE = 'CHAT_DELETE',
  CHAT_GET = 'CHAT_GET',
  CHAT_LIST_CHATS = 'CHAT_LIST_CHATS',
  CHAT_LOAD_MESSAGES = 'CHAT_LOAD_MESSAGES',
  CHAT_LOAD_TABS = 'CHAT_LOAD_TABS',
  CHAT_OPEN = 'CHAT_OPEN',
  CHAT_SAVE_TABS = 'CHAT_SAVE_TABS',
  CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE',
  CHAT_SEND_MESSAGE_STREAM = 'CHAT_SEND_MESSAGE_STREAM',
  ENV_GET = 'ENV_GET',
  MODEL_LIST = 'MODEL_LIST',
  PROMPT_SELECT = 'PROMPT_SELECT',
  SETTINGS_LOAD = 'SETTINGS_LOAD',
  SETTINGS_SAVE = 'SETTINGS_SAVE',
}
